spring.application.name=user-service
# lalitdk


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=lalit

# # PostgreSQL Driver
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA Settings
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
server.port=9091


jwt.secretKey = aefgewjfeajryqefghabkashfukadsbvjkadsbufkjasdbkdfhajdsbvjksdfurehy744rgsdgdthdfh
